spring:
  datasource:
    url: jdbc:mariadb://${MYSQL_DATABASE_URL}:3306/memory
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        globally_quoted_identifiers: true
        format_sql: true
#        dialect: org.hibernate.dialect.MariaDBDialect
#        naming:
#          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#secrete: ${SPRING_SECURITY_SECRETE}
#secrete: likelion